package com.lucascode.OOP;

import java.util.Objects;
//ALL here generated by code generation from the inteliJ


public class Cat2CodeGenerated {
    private String name;
    private int age;
    private String color;



    //Default constructor


    public Cat2CodeGenerated() {
    }

    //Generate constructor
    public Cat2CodeGenerated(String name, String color, int age) {
        this.name = name;
        this.color = color;
        this.age = age;
    }

    //getter and setters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    @Override
    public String toString() {
        return "Cat2CodeGenerated{" +
                "name='" + name + '\'' +
                ", age=" + age +
                ", color='" + color + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Cat2CodeGenerated that = (Cat2CodeGenerated) o;
        return age == that.age && Objects.equals(name, that.name) && Objects.equals(color, that.color);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, age, color);
    }
}


